version: "3"

services:
  node_app:
    build:
      context: .
    image: basis_node
    container_name: basis_node
    restart: always
    ports:
      - "1563:1563"
      - "1564:1564"
      - "1565:1565"
   # volumes:
     